version: '3'
services:
  runner:
    build: .
    environment:
      - ORGANIZATION=*****
      - ACCESS_TOKEN=*****
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 2
    restart: always
